### PR TITLE
[charts/csi-vxflexos]:2.7.0 csi-vxflexos support for helm in csm-installation-wizard

### PR DESCRIPTION
**Pull request by VamsiSiddu-7**
#### Is this a new chart?

No

#### What this PR does / why we need it:
To support csi-powerflex-driver 2.7.0

#### Which issue(s) is this PR associated with:

- #Issue_Number

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [x] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

### CODE REVIEW

**Review by chaganti-rajitha — COMMENTED** [review]
Please change version in values.yaml of container-storage-modules chart.

**Comment by VamsiSiddu-7** [comment]
> Please change version in values.yaml of container-storage-modules chart.

Done

**Review by khareRajshree — APPROVED** [review]

**Review by chaganti-rajitha — APPROVED** [review]
lgtm

**Review by niranjan-n1 — APPROVED** [review]
LGTM

**Pull request merged**
