### PR TITLE
Add kubelinter scans for all charts

### PR DESCRIPTION
**Pull request by mdutka-dell**
#### Is this a new chart?

No

#### Which issue(s) is this PR associated with:

- #Issue_Number

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

### CODE REVIEW

**Comment by mdutka-dell** [comment]
I group applications into three sections: **csi**, **cosi** and **modules**. Each section has its own KubeLinter configuration. KubeLinter supports 51 different checks, but I assume that some checks can be adequate for **csi drivers** and other for **modules**. We could also apply proposals:
1) one kublinter config file for all charts
2) config file per chart

**Comment by shaynafinocchiaro** [comment]
Hi @mdutka-dell, it looks like this PR has gone stale. Is it alright to close it?

**Comment by mdutka-dell** [comment]
> Hi @mdutka-dell, it looks like this PR has gone stale. Is it alright to close it?

Well, we recently discussed how to test and provide best practices to our charts. It's worth to discuss the implementation of the `kubelinter`.

**Comment by shaynafinocchiaro** [comment]
Closing PR since it has been inactive for some time. If we would like to implement kubelinter on our charts, we can reopen this PR.

**Pull request closed without merging**
